---
name: taplo
description: A versatile, feature-rich TOML toolkit.
homepage: https://taplo.tamasfe.dev/
licenses:
  - MIT
languages:
  - TOML
categories:
  - LSP

source:
  id: pkg:github/tamasfe/taplo@0.9.3
  build:
    - target: unix
      run: cargo build -r
      bin: target/release/taplo
    - target: win
      run: cargo build -r
      bin: target/release/taplo.exe

bin:
  taplo: "{{source.build.bin}}"
