---
name: stylua
description: An opinionated Lua code formatter.
homepage: https://github.com/JohnnyMorganz/StyLua
licenses:
  - MPL-2.0
languages:
  - Lua
  - Luau
categories:
  - Formatter

source:
  id: pkg:github/johnnymorganz/stylua@v2.0.2
  build:
    - target: unix
      run: cargo build -r
      bin: target/release/stylua
    - target: win
      run: cargo build -r
      bin: target/release/stylua.exe

  version_overrides:
    - constraint: semver:<=v0.20.0
      id: pkg:github/johnnymorganz/stylua@v0.20.0
      build:
        - target: unix
          run: cargo build -r
          bin: target/release/stylua
        - target: win
          run: cargo build -r
          bin: target/release/stylua.exe

    - constraint: semver:<=v0.19.1
      id: pkg:github/johnnymorganz/stylua@v0.19.1
      build:
        - target: unix
          run: cargo build -r
          bin: target/release/stylua
        - target: win
          run: cargo build -r
          bin: target/release/stylua.exe

bin:
  stylua: "{{source.build.bin}}"
