---
name: shfmt
description: A shell formatter (sh/bash/mksh).
homepage: https://github.com/mvdan/sh
licenses:
  - BSD-3-Clause
languages:
  - Bash
  - Mksh
  - Shell
categories:
  - Formatter

source:
  id: pkg:golang/mvdan.cc/sh/v3/cmd/shfmt@v3.11.0

bin:
  shfmt: "golang:shfmt"
